export const products = [
  {
    id: 1,
    category: "fruits",
    name: "Avocadoes",
    price: "Ksh.150",
    stock: 20,
    ratings: 4,
    ratingsCount: 3725,
    desc: "Approximately 6 pieces per kg",
    img: "src/assets/images/fruits/avocado.jpg",
    shipping: 1,
    quantity: 1,
  },
  {
    id: 2,
    category: "fruits",
    name: "Apples",
    price: "Ksh.180",
    stock: 19,
    ratings: 5,
    ratingsCount: 4355,
    img: "src/assets/images/fruits/apple.jpg",
    shipping: 14,
    quantity: 1,
  },
  {
    id: 3,
    category: "fruits",
    name: "Oranges",
    price: "Ksh.100",
    stock: 20,
    ratings: 4,
    ratingsCount: 3972,
    img: "src/assets/images/fruits/orange.jpg",
    shipping: 1,
    quantity: 1,
  },
  {
    id: 4,
    category: "fruits",
    name: "Bananas",
    price: "Ksh.100",
    stock: 10,
    ratings: 5,
    ratingsCount: 1764,
    desc: "Approximately 6 pieces per kg",
    img: "src/assets/images/fruits/banana.jpg",
    shipping: 32,
    quantity: 1,
  },
  {
    id: 5,
    category: "fruits",
    name: "Mangoes",
    price: "Ksh.139",
    stock: 11,
    ratings: 4,
    ratingsCount: 799,
    img: "src/assets/images/fruits/mangoes.jpg",
    shipping: 49,
    quantity: 1,
  },
  {
    id: 6,
    category: "fruits",
    name: "Strawberries",
    price: "Ksh.240",
    stock: 19,
    ratings: 3,
    ratingsCount: 4372,
    img: "src/assets/images/fruits/strawberries.jpg",
    shipping: 19,
    quantity: 1,
  },
  {
    id: 7,
    category: "fruits",
    name: "Pineapple",
    price: "Ksh.250",
    stock: 1,
    ratings: 4,
    ratingsCount: 2870,
    img: "src/assets/images/fruits/pineapple.jpg",
    shipping: 15,
    quantity: 1,
  },
  {
    id: 8,
    category: "fruits",
    name: "Watermelon",
    price: "Ksh.200",
    stock: 7,
    ratings: 4,
    ratingsCount: 1360,
    img: "src/assets/images/fruits/watermelon.jpg",
    shipping: 50,
    quantity: 1,
  },
  {
    id: 9,
    category: "fruits",
    name: "Papayas",
    price: "Ksh.75",
    stock: 4,
    ratings: 5,
    ratingsCount: 1976,
    img: "src/assets/images/fruits/papaya.jpg",
    shipping: 46,
    quantity: 1,
  },
  {
    id: 10,
    category: "fruits",
    name: "Red Grapes",
    price: "Ksh.412",
    stock: 1,
    ratings: 4,
    ratingsCount: 565,
    img: "src/assets/images/fruits/banana.jpg",
    shipping: 36,
    quantity: 1,
  },
  {
    id: 11,
    category: "fruits",
    name: "Pixies",
    price: "Ksh.120",
    stock: 15,
    ratings: 5,
    ratingsCount: 3702,
    img: "src/assets/images/fruits/pixies.jpg",
    shipping: 29,
    quantity: 1,
  },
  {
    id: 12,
    category: "fruits",
    name: "Peaches",
    price: "Ksh.799",
    stock: 19,
    ratings: 3,
    ratingsCount: 471,
    img: "src/assets/images/fruits/peach.jpg",
    shipping: 20,
    quantity: 1,
  },
  {
    id: 13,
    category: "fruits",
    name: "Green Grapes",
    price: "Ksh.412",
    stock: 7,
    ratings: 5,
    ratingsCount: 37,
    img: "src/assets/images/fruits/green-grapes.jpg",
    shipping: 48,
    quantity: 1,
  },
  {
    id: 14,
    category: "vegetables",
    name: "Tomatoes",
    price: "Ksh.100",
    stock: 6,
    ratings: 5,
    ratingsCount: 1688,
    img: "src/assets/images/vegetables/tomatoes.jpg",
    shipping: 48,
    quantity: 1,
  },
  {
    id: 15,
    category: "vegetables",
    name: "Spring Onions",
    price: "Ksh.100",
    stock: 46,
    ratings: 4,
    ratingsCount: 50,
    img: "src/assets/images/vegetables/spring-onion.jpg",
    shipping: 20,
    quantity: 1,
  },
  {
    id: 16,
    category: "vegetables",
    name: "Red Onions",
    price: "Ksh.105",
    stock: 41,
    ratings: 3,
    ratingsCount: 4483,
    img: "src/assets/images/vegetables/red-onion.jpg",
    shipping: 8,
    quantity: 1,
  },
  {
    id: 17,
    category: "vegetables",
    name: "White Onions",
    price: "Ksh.120",
    stock: 43,
    ratings: 4,
    ratingsCount: 1239,
    img: "src/assets/images/vegetables/white-onions.jpg",
    shipping: 27,
    quantity: 1,
  },
  {
    id: 18,
    category: "vegetables",
    name: "White Cabbage",
    price: "Ksh.150",
    stock: 26,
    ratings: 5,
    ratingsCount: 4557,
    img: "src/assets/images/vegetables/white-cabbage.jpg",
    quantity: 1,
  },
  {
    id: 19,
    category: "vegetables",
    name: "Sweet Potatoes",
    price: "Ksh.150",
    stock: 5,
    ratings: 3,
    ratingsCount: 3383,
    img: "src/assets/images/vegetables/tomatoes.jpg",
    shipping: 26,
    quantity: 1,
  },
  {
    id: 20,
    category: "vegetables",
    name: "English Cucumbers",
    price: "Ksh.80",
    stock: 27,
    ratings: 3,
    ratingsCount: 1974,
    img: "src/assets/images/vegetables/cucumber.jpg",
    shipping: 20,
    quantity: 1,
  },
  {
    id: 21,
    category: "vegetables",
    name: "Butternut Pumpkin",
    price: "Ksh.100",
    stock: 41,
    ratings: 5,
    ratingsCount: 2140,
    img: "src/assets/images/vegetables/butternut.jpg",
    shipping: 49,
    quantity: 1,
  },
  {
    id: 22,
    category: "vegetables",
    name: "Coriander/Dhania",
    price: "Ksh.15",
    stock: 43,
    ratings: 5,
    ratingsCount: 2676,
    img: "src/assets/images/vegetables/coriander.jpg",
    quantity: 1,
  },
  {
    id: 23,
    category: "vegetables",
    name: "Green Peppers",
    price: "Ksh.70",
    stock: 1,
    ratings: 3,
    ratingsCount: 128,
    img: "src/assets/images/vegetables/green-bell-pepper.jpg",
    shipping: 13,
    quantity: 1,
  },
  {
    id: 24,
    category: "vegetables",
    name: "Carrots",
    price: "Ksh.150",
    stock: 19,
    ratings: 4,
    ratingsCount: 894,
    img: "src/assets/images/vegetables/carrot.jpg",
    shipping: 27,
    quantity: 1,
  },
  {
    id: 25,
    category: "juices",
    name: "Pineapple Juice",
    price: "Ksh.260",
    stock: 5,
    ratings: 4,
    ratingsCount: 445,
    img: "src/assets/images/juices/pineapple-juice.jpg",
    shipping: 19,
    quantity: 1,
  },
  {
    id: 26,
    category: "juices",
    name: "Strawberry Juice",
    price: "Ksh.280",
    stock: 10,
    ratings: 5,
    ratingsCount: 83,
    img: "src/assets/images/juices/strawberry-juice.jpg",
    shipping: 24,
    quantity: 1,
  },
  {
    id: 27,
    category: "juices",
    name: "Passion Juice",
    price: "Ksh.250",
    stock: 6,
    ratings: 4,
    ratingsCount: 4,
    img: "src/assets/images/juices/passion-juice.jpg",
    shipping: 1,
    quantity: 1,
  },
  {
    id: 28,
    category: "juices",
    name: "Watermelon Juice",
    price: "Ksh.240",
    stock: 13,
    ratings: 4,
    ratingsCount: 1,
    img: "src/assets/images/juices/watermelon-juice.jpg",
    shipping: 26,
    quantity: 1,
  },
  {
    id: 29,
    category: "juices",
    name: "Apple Juice",
    price: "Ksh.260",
    stock: 18,
    ratings: 3,
    ratingsCount: 39,
    img: "src/assets/images/juices/apple-juice.jpg",
    shipping: 32,
    quantity: 1,
  },
  {
    id: 30,
    category: "juices",
    name: "Orange Juice",
    price: "Ksh.250",
    stock: 1,
    ratings: 4,
    ratingsCount: 14,
    img: "src/assets/images/juices/orange-juice.jpg",
    shipping: 48,
    quantity: 1,
  },
  {
    id: 31,
    category: "juices",
    name: "Grapefruit Juice",
    price: "Ksh.300",
    stock: 10,
    ratings: 5,
    ratingsCount: 47,
    img: "src/assets/images/juices/grapefruit-juice.jpg",
    shipping: 24,
    quantity: 1,
  },

  {
    id: 32,
    category: "bread",
    name: "Baguette",
    price: "Ksh.120",
    stock: 9,
    ratings: 5,
    ratingsCount: 15,
    img: "src/assets/images/bread/baguette.jpg",
    shipping: 6,
    quantity: 1,
  },
  {
    id: 33,
    category: "bread",
    name: "Wholewheat Bread",
    price: "Ksh.300",
    stock: 14,
    ratings: 4,
    ratingsCount: 3,
    img: "src/assets/images/bread/wholewheat.jpg",
    shipping: 14,
    quantity: 1,
  },
  {
    id: 34,
    category: "bread",
    name: "Sourdough Bread",
    price: "Ksh.300",
    stock: 14,
    ratings: 4,
    ratingsCount: 32,
    img: "src/assets/images/bread/sourdough.jpg",
    shipping: 47,
    quantity: 1,
  },
  {
    id: 35,
    category: "bread",
    name: "Multigrain Bread",
    price: "Ksh.280",
    stock: 16,
    ratings: 4,
    ratingsCount: 30,
    img: "src/assets/images/bread/multigrain.jpg",
    shipping: 14,
    quantity: 1,
  },
  {
    id: 36,
    category: "bread",
    name: "Pita Bread",
    price: "Ksh.250",
    stock: 11,
    ratings: 5,
    ratingsCount: 22,
    img: "src/assets/images/bread/pita.jpg",
    shipping: 23,
    quantity: 1,
  },
  {
    id: 37,
    category: "bread",
    name: "White Bread",
    price: "Ksh.250",
    stock: 16,
    ratings: 5,
    ratingsCount: 51,
    img: "src/assets/images/bread/white.jpg",
    shipping: 30,
    quantity: 1,
  },
  {
    id: 38,
    category: "cheese",
    name: "Feta (250g)",
    price: "Ksh.500",
    stock: 7,
    ratings: 5,
    ratingsCount: 365,
    img: "src/assets/images/cheese/feta.jpg",
    shipping: 23,
    quantity: 1,
  },
  {
    id: 39,
    category: "cheese",
    name: "Mozzarella (200g)",
    price: "Ksh.600",
    stock: 3,
    ratings: 4,
    ratingsCount: 465,
    img: "src/assets/images/cheese/mozzarella.jpg",
    shipping: 36,
    quantity: 1,
  },
  {
    id: 40,
    category: "cheese",
    name: "Gouda (200g)",
    price: "Ksh.670",
    stock: 10,
    ratings: 3,
    ratingsCount: 346,
    img: "src/assets/images/cheese/gouda.jpg",
    shipping: 42,
    quantity: 1,
  },
  {
    id: 41,
    category: "cheese",
    name: "Manchego (100g)",
    price: "Ksh.1300",
    stock: 15,
    ratings: 5,
    ratingsCount: 234,
    img: "src/assets/images/cheese/manchego.jpg",
    shipping: 21,
    quantity: 1,
  },
  {
    id: 42,
    category: "cheese",
    name: "Brie (125g)",
    price: "Ksh.725",
    stock: 10,
    ratings: 4,
    ratingsCount: 241,
    img: "src/assets/images/cheese/brie.jpg",
    shipping: 15,
    quantity: 1,
  },
  {
    id: 43,
    category: "cheese",
    name: "Camembert (200g)",
    price: "Ksh.755",
    stock: 18,
    ratings: 5,
    ratingsCount: 168,
    img: "src/assets/images/cheese/camembert.jpg",
    shipping: 14,
    quantity: 1,
  },
  {
    id: 44,
    category: "cheese",
    name: "Montagnolo (200g)",
    price: "Ksh.750",
    stock: 16,
    ratings: 3,
    ratingsCount: 311,
    img: "src/assets/images/cheese/montagnolo.jpg",
    shipping: 40,
    quantity: 1,
  },
  {
    id: 45,
    category: "cheese",
    name: "Parmesan (200g)",
    price: "Ksh.1700",
    stock: 8,
    ratings: 4,
    ratingsCount: 66,
    img: "src/assets/images/cheese/parmesan.jpg",
    shipping: 15,
    quantity: 1,
  },
  {
    id: 46,
    category: "cheese",
    name: "Cheddar (100g)",
    price: "Ksh.416",
    stock: 14,
    ratings: 4,
    ratingsCount: 6,
    img: "src/assets/images/cheese/cheddar.jpg",
    shipping: 29,
    quantity: 1,
  },
  {
    id: 47,
    category: "smoothies",
    name: "Mango Smoothie",
    price: "Ksh.200",
    stock: 6,
    ratings: 5,
    ratingsCount: 354,
    img: "src/assets/images/smoothies/mango-smoothie.jpg",
    shipping: 26,
    quantity: 1,
  },
  {
    id: 48,
    category: "smoothies",
    name: "Banana Smoothie",
    price: "Ksh.200",
    stock: 3,
    ratings: 4,
    ratingsCount: 584,
    img: "src/assets/images/smoothies/banana-smoothie.jpg",
    shipping: 33,
    quantity: 1,
  },
  {
    id: 49,
    category: "smoothies",
    name: "Green Smoothie",
    price: "Ksh.280",
    stock: 13,
    ratings: 3,
    ratingsCount: 1010,
    img: "src/assets/images/smoothies/green-smoothie.jpg",
    shipping: 4,
    quantity: 1,
  },
  {
    id: 50,
    category: "smoothies",
    name: "Banana Almond Smoothie",
    price: "Ksh.350",
    stock: 14,
    ratings: 4,
    ratingsCount: 2422,
    img: "src/assets/images/smoothies/banana-almond-smoothie.jpg",
    shipping: 39,
    quantity: 1,
  },
  {
    id: 51,
    category: "smoothies",
    name: "Papaya Smoothie",
    price: "Ksh.250",
    stock: 16,
    ratings: 3,
    ratingsCount: 1533,
    img: "src/assets/images/smoothies/papaya-smoothie.jpg",
    shipping: 33,
    quantity: 1,
  },
  {
    id: 52,
    category: "smoothies",
    name: "Strawberry Smoothie",
    price: "Ksh.260",
    stock: 15,
    ratings: 5,
    ratingsCount: 9,
    img: "src/assets/images/smoothies/strawb-smoothie.jpg",
    shipping: 48,
    quantity: 1,
  },
  {
    id: 53,
    category: "smoothies",
    name: "Kiwi Smoothie",
    price: "Ksh.400",
    stock: 15,
    ratings: 5,
    ratingsCount: 55,
    img: "src/assets/images/smoothies/kiwi-smoothie.jpg",
    shipping: 48,
    quantity: 1,
  },
];
